# Creating a matrix

In [2]:
A<- matrix(data=c(-11,0,99,88,88,-1,1,0),nrow=4,ncol=2,byrow=TRUE)

In [3]:
print(A)

     [,1] [,2]
[1,]  -11    0
[2,]   99   88
[3,]   88   -1
[4,]    1    0


In [5]:
rbind(-2:7,0:9)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] -2   -1   0    1    2    3    4    5    6    7    
[2,]  0    1   2    3    4    5    6    7    8    9

In [6]:
cbind(c(1:6),c(2:7),c(3:8))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 2    3    4   
[3,] 3    4    5   
[4,] 4    5    6   
[5,] 5    6    7   
[6,] 6    7    8

# Dimension of a matrix

In [15]:
print(A)

     [,1] [,2]
[1,]  -11    0
[2,]   99   88
[3,]   88   -1
[4,]    1    0


In [7]:
dim(A)

[1] 4 2

In [8]:
nrow(A)

[1] 4

In [9]:
ncol(A)

[1] 2

In [11]:
dim(A)[1]

[1] 4

# Extratcing elements of a matrix

In [14]:
print(A[4,2])

[1] 0

In [17]:
print(A[,c(2,1)])

     [,1] [,2]
[1,]    0  -11
[2,]   88   99
[3,]   -1   88
[4,]    0    1


In [18]:
print(A[2,])

[1] 99 88


In [19]:
print(A[,2])

[1]  0 88 -1  0


In [20]:
print(A[2:4])

[1] 99 88  1


# Manipulating Matrix


In [22]:
print(A[,-1])

[1]  0 88 -1  0


In [23]:
print(A)

     [,1] [,2]
[1,]  -11    0
[2,]   99   88
[3,]   88   -1
[4,]    1    0


In [24]:
print(A[-1,-2])

[1] 99 88  1


In [25]:
b<-A

In [26]:
print(b)

     [,1] [,2]
[1,]  -11    0
[2,]   99   88
[3,]   88   -1
[4,]    1    0


In [27]:
b[2,]<-c(1,0)

In [28]:
print(b)

     [,1] [,2]
[1,]  -11    0
[2,]    1    0
[3,]   88   -1
[4,]    1    0


In [30]:
b[c(2,3),2:1]<-c(99,0,1,2)
print(b)

     [,1] [,2]
[1,]  -11    0
[2,]    1   99
[3,]    2    0
[4,]    1    0


In [32]:
diag(x=b)<-rep(x=0,times=2)

In [33]:
print(b)

     [,1] [,2]
[1,]    0    0
[2,]    1    0
[3,]    2    0
[4,]    1    0
